### ISSUE TITLE
Vignette scene blocks mouse input

### ISSUE THREAD

**Issue by HalfHeardGames** [ItsKorin/Godot-Post-Process-Plugin#1]
Version: 0.0.4
Simple enough to fix, but the vignette scene's data note is set to mouse_filter STOP by default, which blocks all mouse input. Took me a little while to figure out what was going on. Since the vignette is usually on top of everything, it should definitely not be set to "STOP" mouse input. Please change to "ignore" or at least "pass" to correct the default setting.

**Comment by KorinDev** [comment]
Sorry for responding so late.
i actually ran into the same issue this week while adding UI to my own game that i use my addon/plugin in.

I Will release the fixed version in next 5 to 10 hours since i just woke up.

The Github release releases faster than the Godot Asset Store one, since the Godot Asset Store asset takes around 10 hours to update by itself.

Thank you, and the release should be ready soon!

**Comment by KorinDev** [comment]
Issue fixed with [v0.0.5](https://github.com/ItsKorin/Godot-Post-Process-Plugin/releases/tag/v0.0.5)
Have fun!
